version: '3.7'

services:
  pg:
    image: postgres:latest
    container_name: fake-tweet-app
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: faketweetapp
    volumes:
        - ./data:/var/lib/postgresql/data

volumes:
    data: {}