spring:
  application:
    name: FakeTweetAppDev
  datasource:
    url: jdbc:postgresql://localhost:5000/
    username: postgres
    password: Ali20031001a
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
# This section is for the JWT token
jwt:
  secret-key: dGhpcyBpcyB0b3Agc2VjcmV0IGtleSBmb3IgbXkgcHJvamVjdA==
  expiration: 86400000*3 # 3 days


